/*
 * ActionTechSpecImpl.java
 *
 * Created on April 5, 2004, 3:15 PM
 * <copyright>
 *  Copyright 2004 Object Services and Consulting, Inc.
 *  under sponsorship of the Defense Advanced Research Projects
 *  Agency (DARPA).
 *
 *  You can redistribute this software and/or modify it under the
 *  terms of the Cougaar Open Source License as published on the
 *  Cougaar Open Source Website (www.cougaar.org).
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * </copyright>
 */

package org.cougaar.coordinator.techspec;

import org.cougaar.coordinator.*;
import org.cougaar.core.util.UID;

import java.util.Set;
import java.util.HashSet;
import java.util.Vector;
import java.util.Iterator;

/**
 *
 * @author  Administrator
 */
public class ActionTechSpecImpl implements ActionTechSpecInterface   {

    String name;
    UID uid;
    AssetType assetType;
    String assetDim;
    Vector actions;
    String revision = "0.1";
    
    HashSet possibleValues = null;
    
    /** Creates a new instance of ActionTechSpecImpl */
    public ActionTechSpecImpl(String name, UID uid, AssetType type, String assetDim) {

        this.name = name;
        this.uid = uid;
        this.assetType = assetType;
        this.assetDim = assetDim;
        
        actions = new Vector();
        possibleValues = new HashSet();
    }
    
    /**
     * @return the name of this ActionTechSpec
     */
    public String getName() { return name; }

    /**
     * @return the uid of this ActionTechSpec
     */
    public UID getUID() { return uid; }
    
    /**
     * @return  the possible values that Actions generated by this Actuator can return via getValue()
     */
    public Set getPossibleValues() { return possibleValues; }
    
    /**
     * @return the asset type that the actuator cares about.
     */
    public AssetType getAssetType() { return assetType; }
    
    /**
     * @return the state dimension that the actuator affects if an action is taken.
     */
    public AssetStateDimension getStateDimension() { 
        
        //Evaluate lazily as the state dim. may not be defined when this action is loaded from xml
        return assetType.findStateDimension(assetDim);
    }
    
    /**
     * @return the ActionDescriptions for this Actuator
     */
    public Vector getActions() { return actions; }

    /**
     * Add an action
     */
    public void addAction(ActionDescription ad) { 
        actions.add(ad); 
        possibleValues.add( ad.name() );
    }
    
    /** @return a revision string for this TechSpec
     *
     */
    public void setRevision(String r) {
        this.revision = r;
    }

    /** @return a revision string for this TechSpec
     *
     */
    public String getRevision() {
        return revision;
    }
    
}
