/*
 * ActionTechSpecInterface.java
 *
 * Created on July 9, 2003, 9:24 AM
 * <copyright>
 *  Copyright 2003 Object Services and Consulting, Inc.
 *  under sponsorship of the Defense Advanced Research Projects Agency (DARPA)
 *  and the Defense Logistics Agency (DLA).
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the Cougaar Open Source License as published by
 *  DARPA on the Cougaar Open Source Website (www.cougaar.org).
 * 
 *  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
 *  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
 *  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
 *  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
 *  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
 *  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
 *  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *  PERFORMANCE OF THE COUGAAR SOFTWARE.
 * </copyright>
 */

package org.cougaar.coordinator.techspec;
import java.util.Vector;
import java.util.Set;

/**
 *
 * @author  Paul Pazandak, Ph.D. OBJS, Inc.
 */
public interface ActionTechSpecInterface extends TechSpecRootInterface {

    
    /**
     * @return  the possible values that Actions generated by this Actuator can return via getValue()
     */
    public Set getPossibleValues();
    
    /**
     * @return the asset type that the actuator cares about.
     */
    public AssetType getAssetType();
    
    /**
     * @return the state dimension that the actuator affects if an action is taken.
     */
    public AssetStateDimension getStateDimension();
    
    /**
     * @return the ActionDescriptions for this Actuator
     */
    public Vector getActions();

    /**
     * Add an action
     */
    public void addAction(ActionDescription ad);
    
    
    
}
