/*
 * File:           DefenseXMLParser.java
 * Date:           September 17, 2003  4:37 PM
 *
 * <copyright>
 *  Copyright 2003 Object Services and Consulting, Inc.
 *  under sponsorship of the Defense Advanced Research Projects Agency (DARPA)
 *  and the Defense Logistics Agency (DLA).
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the Cougaar Open Source License as published by
 *  DARPA on the Cougaar Open Source Website (www.cougaar.org).
 * 
 *  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
 *  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
 *  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
 *  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
 *  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
 *  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
 *  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *  PERFORMANCE OF THE COUGAAR SOFTWARE.
 * </copyright>
 * @author  Administrator
 * @version generated by NetBeans XML module
 */
package org.cougaar.coordinator.techspec;

import org.cougaar.util.log.Logger;
import org.cougaar.util.log.Logging;
import org.cougaar.core.service.UIDService;

import org.xml.sax.*;
import org.xml.sax.EntityResolver;
import org.xml.sax.InputSource;
import java.io.File;
import java.io.FileInputStream;
import java.util.Vector;

import org.cougaar.util.ConfigFinder; //steve

/**
 * The class reads XML documents according to specified DTD 
 * <p>Usage sample:
 * <pre>
 *    DefenseXMLParser parser = new DefenseXMLParser();
 *    parser.parse(new InputSource("..."));
 * </pre>
 */
public class DefenseXMLParser implements ContentHandler {
    
    private java.lang.StringBuffer buffer;
       
    private java.util.Stack context;
    
    private EntityResolver resolver;
    
    Vector newDefenses;
    
    private Logger logger;
    
    public Vector getParsedDefenses() { return newDefenses; }
    
    private UIDService uid;
    
    /**
     * Creates a parser instance.
     */
    public DefenseXMLParser(UIDService uid) { //, final EntityResolver resolver) { //, final ThreatModelXML_DTDParsletInterface parslet) {
        //this.parslet = parslet;
        this.resolver = new MyResolver();
        buffer = new StringBuffer(111);
        context = new java.util.Stack();
        
        newDefenses = new Vector();
        logger = Logging.getLogger(this.getClass().getName());
        
        this.uid = uid;
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void setDocumentLocator(Locator locator) {
        //handler.setDocumentLocator(locator);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void startDocument() throws SAXException {
        //handler.startDocument();
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void endDocument() throws SAXException {
        //handler.endDocument();
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void startElement(java.lang.String ns, java.lang.String name, java.lang.String qname, Attributes attrs) throws SAXException {
        dispatch(true);
        context.push(new Object[] {qname, new org.xml.sax.helpers.AttributesImpl(attrs)});
        if ("DefenseXML".equalsIgnoreCase(qname)) {
            ;
        } else if ("Defense".equalsIgnoreCase(qname)) {
            start_Defense(attrs);
        } else if ("Monitoring".equalsIgnoreCase(qname)) {
            ;
        } else if ("Level".equalsIgnoreCase(qname)) {
            start_Level(attrs);
        } else if ("DiagnosisAccuracy".equalsIgnoreCase(qname)) {
            ;
        } else if ("Function".equalsIgnoreCase(qname)) {
            handle_Function(attrs);
        } 
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void endElement(java.lang.String ns, java.lang.String name, java.lang.String qname) throws SAXException {
        dispatch(false);
        context.pop();
        if ("DefenseXML".equalsIgnoreCase(qname)) {
            ;
        } else if ("Defense".equalsIgnoreCase(qname)) {
            end_Defense();
        } else if ("Monitoring".equalsIgnoreCase(qname)) {
            ;
        } else if ("Level".equalsIgnoreCase(qname)) {
            end_Level();
        } else if ("DiagnosisAccuracy".equalsIgnoreCase(qname)) {
            ;
        } 
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void characters(char[] chars, int start, int len) throws SAXException {
        buffer.append(chars, start, len);
        //handler.characters(chars, start, len);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void ignorableWhitespace(char[] chars, int start, int len) throws SAXException {
        //handler.ignorableWhitespace(chars, start, len);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void processingInstruction(java.lang.String target, java.lang.String data) throws SAXException {
        //handler.processingInstruction(target, data);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void startPrefixMapping(final java.lang.String prefix, final java.lang.String uri) throws SAXException {
        //handler.startPrefixMapping(prefix, uri);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void endPrefixMapping(final java.lang.String prefix) throws SAXException {
        //handler.endPrefixMapping(prefix);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void skippedEntity(java.lang.String name) throws SAXException {
        //handler.skippedEntity(name);
    }
    
    private void dispatch(final boolean fireOnlyIfMixed) throws SAXException {
        if (fireOnlyIfMixed && buffer.length() == 0) return; //skip it
        
        Object[] ctx = (Object[]) context.peek();
        String here = (String) ctx[0];
        Attributes attrs = (Attributes) ctx[1];
        buffer.delete(0, buffer.length());
    }
    
    /**
     * The recognizer entry method taking an InputSource.
     * @param input InputSource to be parsed.
     * @throws java.io.IOException on I/O error.
     * @throws SAXException propagated exception thrown by a DocumentHandler.
     * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
     * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
     */
    public void parse(final InputSource input) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
        parse(input, this);
    }
    
    /**
     * The recognizer entry method taking a URL.
     * @param url URL source to be parsed.
     * @throws java.io.IOException on I/O error.
     * @throws SAXException propagated exception thrown by a DocumentHandler.
     * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
     * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
     */
    public void parse(final java.net.URL url) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
        parse(new InputSource(url.toExternalForm()), this);
    }
    
    
    private static void parse(final InputSource input, final DefenseXMLParser recognizer) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
        javax.xml.parsers.SAXParserFactory factory = javax.xml.parsers.SAXParserFactory.newInstance();
        factory.setValidating(true);  //the code was generated according DTD
        factory.setNamespaceAware(false);  //the code was generated according DTD
        XMLReader parser = factory.newSAXParser().getXMLReader();
        parser.setContentHandler(recognizer);
        parser.setErrorHandler(recognizer.getDefaultErrorHandler());
        if (recognizer.resolver != null) parser.setEntityResolver(recognizer.resolver);
        parser.parse(input);
    }
    
    
    /**
     * Creates default error handler used by this parser.
     * @return org.xml.sax.ErrorHandler implementation
     */
    protected ErrorHandler getDefaultErrorHandler() {
        return new ErrorHandler() {
            public void error(SAXParseException ex) throws SAXException  {
                if (context.isEmpty()) System.err.println("Missing DOCTYPE.");
                throw ex;
            }
            
            public void fatalError(SAXParseException ex) throws SAXException {
                throw ex;
            }
            
            public void warning(SAXParseException ex) throws SAXException {
                // ignore
            }
        };
        
    }


    private DefaultDefenseTechSpec currentDefense;
    private MonitoringLevel currentMonitoringLevel;
    private boolean ERROR = false;

        
    /** Called when the start of the Defense element is seen */
    private void start_Defense(Attributes attrs){ 

        ERROR = false; //reset, start of new descriptor

        String name = attrs.getValue("name");
        String type = attrs.getValue("assetType");        
        String idempotent = attrs.getValue("idempotent");
        String reversible = attrs.getValue("reversible");        
        String abortable = attrs.getValue("abortable");
        String tempCost = attrs.getValue("tempCost");        
        String tempBenefit = attrs.getValue("tempBenefit");
        String stateName = attrs.getValue("affectsAssetState"); 

        try { 

            AssetType assetType = AssetType.findAssetType(type);
            if ( assetType == null) { 
                ERROR = true; 
                logger.warn("*** Cannot process this defense entry -- Defense XML -  unknown asset type = : "+type);            
                return;
            }
            AssetStateDimension assetState = assetType.findStateDimension(stateName);
            if ( assetState == null) { 
                ERROR = true; 
                logger.warn("*** Cannot process this defense entry -- Defense XML -  unknown asset state = : "+stateName + " for this asset type: "+type);            
                return;
            }

            boolean isIdempotent = Boolean.valueOf(idempotent).booleanValue();
            boolean isReversible = Boolean.valueOf(reversible).booleanValue();
            boolean isAbortable = Boolean.valueOf(abortable).booleanValue();

            Double dTempCost  = Double.valueOf(tempCost);
            Double dTempBenefit  = Double.valueOf(tempBenefit);


            if (name != null && !ERROR) {
//3 removed to compile                currentDefense = new DefaultDefenseTechSpec(name, uid.nextUID(), isIdempotent, isReversible, isAbortable, dTempCost.doubleValue(), dTempBenefit.doubleValue(), assetType, assetState);
                currentMonitoringLevel = null;
            } else {
                ERROR = true;
                logger.warn("*** Cannot process this defense entry -- Defense XML -  problem importing defense attrs for defense = : "+name);            
            }
        } catch (NumberFormatException e) {
            ERROR = true;
            logger.warn("*** Cannot process this defense entry -- Defense XML - Defense element - error converting cost or benefit to double. Defense = "+name);            
        }
    }
    
    
    
    /** Called when the start of the Level element is seen */
    private void start_Level(Attributes attrs){ 

        ERROR = false; //reset, start of new descriptor

        String cost = attrs.getValue("cost");
        String name = attrs.getValue("name");        
        String latency = attrs.getValue("latency");        

        try {
            Long lLatency = Long.valueOf(latency);
            Double dCost  = Double.valueOf(latency);
        
            if (name != null) {
                currentMonitoringLevel = new MonitoringLevel(name, lLatency.longValue(), dCost.doubleValue());
            } else {
                ERROR = true;
                logger.warn("*** Cannot process -- Defense XML:Level element -  name=" + name );            
            }
        } catch (Exception e) {
            ERROR = true;
            logger.warn("*** Cannot process -- Defense XML:Level element - conversion exception with latency(Long) or cost(Double) for Defense = "+ currentDefense.getName());            
        }
    }
    
    
    /** Called when the Function element is seen */
    private void handle_Function(Attributes attrs){ 
    
        if (ERROR) { return; }
        if (currentMonitoringLevel == null) {
            ERROR = true;
            logger.warn("*** Cannot process -- Defense XML:Function element - Missing Monitoring element.");            
            return;
        }

        String diagnosis = attrs.getValue("diagnosis");
        String state = attrs.getValue("assetStateDescriptor");        
        String value = attrs.getValue("assetStateValue");        
        String prob = attrs.getValue("probability");        
        String type = attrs.getValue("assetType");        

        AssetType assetType = null;
        if ( type == null) { //use type specified in Defense element
            assetType = currentDefense.getAssetType();
        } else {
            assetType = AssetType.findAssetType(type);
            if (assetType == null) {
                ERROR = true; 
                logger.warn("*** Cannot process this defense entry -- Defense XML -  unknown asset type = : "+type);            
                return;
            }
        }
        
        
        AssetStateDimension assetStateDim = assetType.findStateDimension(state);
        if ( assetStateDim == null) { 
            ERROR = true; 
            logger.warn("*** Cannot process this defense entry -- Defense XML -  unknown asset state = : "+state + " for this asset type: "+assetType.getName());            
            return;
        }
        AssetState stateValue = assetStateDim.findAssetState(value);
        if ( stateValue == null) { 
            ERROR = true; 
            logger.warn("*** Cannot process this defense entry -- Defense XML -  unknown state value = : "+value + " for this asset state = : "+state + " & this asset type: "+assetType.getName());            
            return;
        }
        AssetState diagnosisStateValue = currentDefense.getAffectedAssetState().findAssetState(diagnosis);
        if ( diagnosisStateValue == null) { 
            ERROR = true; 
            logger.warn("*** Cannot process this defense entry -- Defense XML -  unknown diagnosis state value= : "+diagnosis + "for this asset state = : "+state + " & this asset type: "+assetType.getName());            
            return;
        }

        try {
            double probability = Double.parseDouble(prob);
            DiagnosisAccuracyFunction daf = new DiagnosisAccuracyFunction(assetStateDim, stateValue, diagnosisStateValue, probability);
            currentMonitoringLevel.addDiagnosis(daf);
        } catch (Exception e) {
            ERROR = true;
            logger.warn("*** Cannot process -- Defense XML - Function element - probability conversion to double error: p="+prob, e);            
        }
        
        
    }
    
    
    /** Called when the end of the end_AssetStateDimensions element is seen */
    private void end_Defense(){
    
        if (!ERROR) { //add the currentDefense
            newDefenses.addElement(currentDefense);
        }
    }
    


    /** Called when the end of the AssetStates element is seen */
    private void end_Level(){
    
        if (!ERROR) { //add the currentDefense
            currentDefense.addMonitoringLevel(currentMonitoringLevel);
        }
    }
    
    

    /**
     * Used to find local dtd file. Strips off "file://" from the SystemID name
     * supplying the DTD file name.
     *
     */
     public class MyResolver implements EntityResolver {
       public InputSource resolveEntity (String publicId, String systemId)
       {
          System.out.println("SystemID = "+systemId);
          System.out.println("publicID = "+publicId);

//steve   String fn = systemId.substring(7); //strip off "file://"
	  int i = systemId.lastIndexOf('/'); //steve
          String fn = systemId.substring(i+1); //steve
          try {
//steve       return new InputSource(new FileInputStream(new File(fn)));
              return new InputSource(new FileInputStream(new ConfigFinder().locateFile(fn))); //steve
          } catch (Exception e) {
              System.out.println("DTD Exception: "+e);
              return null;
          }
       }
     }
    
}

