/*
 * File:           ThreatModelXML_DTDParser.java
 * Date:           September 17, 2003  4:37 PM
 *
 * <copyright>
 *  Copyright 2003 Object Services and Consulting, Inc.
 *  under sponsorship of the Defense Advanced Research Projects Agency (DARPA)
 *  and the Defense Logistics Agency (DLA).
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the Cougaar Open Source License as published by
 *  DARPA on the Cougaar Open Source Website (www.cougaar.org).
 * 
 *  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
 *  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
 *  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
 *  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
 *  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
 *  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
 *  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *  PERFORMANCE OF THE COUGAAR SOFTWARE.
 * </copyright>
 * @author  Administrator
 * @version generated by NetBeans XML module
 */
package org.cougaar.coordinator.techspec;

import org.xml.sax.*;
import org.xml.sax.EntityResolver;
import org.xml.sax.InputSource;
import java.io.File;
import java.io.FileInputStream;

import org.cougaar.util.ConfigFinder; //steve

/**
 * The class reads XML documents according to specified DTD and
 * translates all related events into ThreatModelXML_DTDHandlerInterface events.
 * <p>Usage sample:
 * <pre>
 *    ThreatModelXML_DTDParser parser = new ThreatModelXML_DTDParser(...);
 *    parser.parse(new InputSource("..."));
 * </pre>
 */
public class ThreatModelXML_DTDParser implements ContentHandler {
    
    private java.lang.StringBuffer buffer;
    
 //   private ThreatModelXML_DTDParsletInterface parslet;
    
    private ThreatModelXML_DTDHandlerInterface handler;
    
    private java.util.Stack context;
    
    private EntityResolver resolver;
    
    /**
     * Creates a parser instance.
     * @param handler handler interface implementation (never <code>null</code>
     * @param resolver SAX entity resolver implementation or <code>null</code>.
     * It is recommended that it could be able to resolve at least the DTD.@param parslet convertors implementation (never <code>null</code>
     */
    public ThreatModelXML_DTDParser(final ThreatModelXML_DTDHandlerInterface handler) { //, final EntityResolver resolver) { //, final ThreatModelXML_DTDParsletInterface parslet) {
        //this.parslet = parslet;
        this.handler = handler;
        this.resolver = new MyResolver();
        buffer = new StringBuffer(111);
        context = new java.util.Stack();
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void setDocumentLocator(Locator locator) {
        //handler.setDocumentLocator(locator);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void startDocument() throws SAXException {
        //handler.startDocument();
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void endDocument() throws SAXException {
        //handler.endDocument();
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void startElement(java.lang.String ns, java.lang.String name, java.lang.String qname, Attributes attrs) throws SAXException {
        dispatch(true);
        context.push(new Object[] {qname, new org.xml.sax.helpers.AttributesImpl(attrs)});
        if ("MemberFilters".equalsIgnoreCase(qname)) {
            handler.start_MemberFilters(attrs);
        } else if ("ThreatModels".equalsIgnoreCase(qname)) {
            handler.start_ThreatModels(attrs);
        } else if ("ThreatModelDef".equalsIgnoreCase(qname)) {
            handler.start_ThreatModelDef(attrs);
        } else if ("ApplicabilityInterval".equalsIgnoreCase(qname)) {
            handler.handle_ApplicabilityInterval(attrs);
        } else if ("Likelihood".equalsIgnoreCase(qname)) {
            handler.start_Likelihood(attrs);
        } else if ("Filter".equalsIgnoreCase(qname)) {
            handler.handle_Filter(attrs);
        } else if ("Distribution".equalsIgnoreCase(qname)) {
            handler.start_Distribution(attrs);
        } else if ("DamageVector".equalsIgnoreCase(qname)) {
            handler.start_DamageVector(attrs);
        } else if ("Transition".equalsIgnoreCase(qname)) {
            handler.handle_Transition(attrs);
        } //else {
//            System.out.println("ns="+ns);
//            System.out.println("name="+name);
//            System.out.println("qname="+qname);
          //  startElement(ns, name, qname, attrs);
//        }
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void endElement(java.lang.String ns, java.lang.String name, java.lang.String qname) throws SAXException {
        dispatch(false);
        context.pop();
        if ("MemberFilters".equals(qname)) {
            handler.end_MemberFilters();
        } else if ("ThreatModels".equalsIgnoreCase(qname)) {
            handler.end_ThreatModels();
        } else if ("ThreatModelDef".equalsIgnoreCase(qname)) {
            handler.end_ThreatModelDef();
        } else if ("Likelihood".equalsIgnoreCase(qname)) {
            handler.end_Likelihood();
        } else if ("Distribution".equalsIgnoreCase(qname)) {
            handler.end_Distribution();
        } else if ("DamageVector".equalsIgnoreCase(qname)) {
            handler.end_DamageVector();
        }
        //endElement(ns, name, qname);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void characters(char[] chars, int start, int len) throws SAXException {
        buffer.append(chars, start, len);
        //handler.characters(chars, start, len);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void ignorableWhitespace(char[] chars, int start, int len) throws SAXException {
        //handler.ignorableWhitespace(chars, start, len);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void processingInstruction(java.lang.String target, java.lang.String data) throws SAXException {
        //handler.processingInstruction(target, data);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void startPrefixMapping(final java.lang.String prefix, final java.lang.String uri) throws SAXException {
        //handler.startPrefixMapping(prefix, uri);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void endPrefixMapping(final java.lang.String prefix) throws SAXException {
        //handler.endPrefixMapping(prefix);
    }
    
    /**
     * This SAX interface method is implemented by the parser.
     */
    public final void skippedEntity(java.lang.String name) throws SAXException {
        //handler.skippedEntity(name);
    }
    
    private void dispatch(final boolean fireOnlyIfMixed) throws SAXException {
        if (fireOnlyIfMixed && buffer.length() == 0) return; //skip it
        
        Object[] ctx = (Object[]) context.peek();
        String here = (String) ctx[0];
        Attributes attrs = (Attributes) ctx[1];
        buffer.delete(0, buffer.length());
    }
    
    /**
     * The recognizer entry method taking an InputSource.
     * @param input InputSource to be parsed.
     * @throws java.io.IOException on I/O error.
     * @throws SAXException propagated exception thrown by a DocumentHandler.
     * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
     * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
     */
    public void parse(final InputSource input) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
        parse(input, this);
    }
    
    /**
     * The recognizer entry method taking a URL.
     * @param url URL source to be parsed.
     * @throws java.io.IOException on I/O error.
     * @throws SAXException propagated exception thrown by a DocumentHandler.
     * @throws javax.xml.parsers.ParserConfigurationException a parser satisfining requested configuration can not be created.
     * @throws javax.xml.parsers.FactoryConfigurationRrror if the implementation can not be instantiated.
     */
    public void parse(final java.net.URL url) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
        parse(new InputSource(url.toExternalForm()), this);
    }
    
    
    private static void parse(final InputSource input, final ThreatModelXML_DTDParser recognizer) throws SAXException, javax.xml.parsers.ParserConfigurationException, java.io.IOException {
        javax.xml.parsers.SAXParserFactory factory = javax.xml.parsers.SAXParserFactory.newInstance();
        factory.setValidating(true);  //the code was generated according DTD
        factory.setNamespaceAware(false);  //the code was generated according DTD
        XMLReader parser = factory.newSAXParser().getXMLReader();
        parser.setContentHandler(recognizer);
        parser.setErrorHandler(recognizer.getDefaultErrorHandler());
        if (recognizer.resolver != null) parser.setEntityResolver(recognizer.resolver);
        parser.parse(input);
    }
    
    
    /**
     * Creates default error handler used by this parser.
     * @return org.xml.sax.ErrorHandler implementation
     */
    protected ErrorHandler getDefaultErrorHandler() {
        return new ErrorHandler() {
            public void error(SAXParseException ex) throws SAXException  {
                if (context.isEmpty()) System.err.println("Missing DOCTYPE.");
                throw ex;
            }
            
            public void fatalError(SAXParseException ex) throws SAXException {
                throw ex;
            }
            
            public void warning(SAXParseException ex) throws SAXException {
                // ignore
            }
        };
        
    }

    

    /**
     * Used to find local dtd file. Strips off "file://" from the SystemID name
     * supplying the DTD file name.
     *
     */
     public class MyResolver implements EntityResolver {
       public InputSource resolveEntity (String publicId, String systemId)
       {
          System.out.println("SystemID = "+systemId);
          System.out.println("publicID = "+publicId);

//steve   String fn = systemId.substring(7); //strip off "file://"
	  int i = systemId.lastIndexOf('/'); //steve
          String fn = systemId.substring(i+1); //steve
          try {
//steve      return new InputSource(new FileInputStream(new File(fn)));
             return new InputSource(new FileInputStream(new ConfigFinder().locateFile(fn))); //steve
          } catch (Exception e) {
              System.out.println("DTD Exception: "+e);
              return null;
          }
       }
     }
    
}

