/*
 * File:           ThreatModelXML_DTDHandlerInterface.java
 * Date:           September 17, 2003  4:37 PM
 *
 * <copyright>
 *  Copyright 2003 Object Services and Consulting, Inc.
 *  under sponsorship of the Defense Advanced Research Projects Agency (DARPA)
 *  and the Defense Logistics Agency (DLA).
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the Cougaar Open Source License as published by
 *  DARPA on the Cougaar Open Source Website (www.cougaar.org).
 * 
 *  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
 *  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
 *  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
 *  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
 *  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
 *  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
 *  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
 *  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 *  PERFORMANCE OF THE COUGAAR SOFTWARE.
 * </copyright>
 * @author  Administrator
 * @version generated by NetBeans XML module
 */
package org.cougaar.coordinator.techspec;

import org.xml.sax.*;

public interface ThreatModelXML_DTDHandlerInterface { //extends ContentHandler {
    
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_Element(java.lang.String ns, java.lang.String name, java.lang.String qname, Attributes attrs) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_Element(java.lang.String ns, java.lang.String name, java.lang.String qname) throws SAXException;

    /**
     * A container element end event handling method.
     */
    public void end_ThreatModels() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_ThreatModels(final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_MemberFilters(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_MemberFilters() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_ThreatModelDef(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_ThreatModelDef() throws SAXException;
    
    /**
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_ApplicabilityInterval(final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_Likelihood(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_Likelihood() throws SAXException;
    
    /**
     * An empty element event handling method.
     * @param data value or null
     */
    public void handle_Filter(final Attributes meta) throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_Distribution(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_Distribution() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_DamageVector(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_DamageVector() throws SAXException;
    
    /**
     * A data element event handling method.
     * @param data value or null
     * @param meta attributes
     */
    public void handle_Transition(final Attributes meta) throws SAXException;
    
}

