/*
 * <copyright>
 * 
 *  Copyright 2003-2004 Object Services and Consulting, Inc.
 *  under sponsorship of the Defense Advanced Research Projects
 *  Agency (DARPA).
 *
 *  You can redistribute this software and/or modify it under the
 *  terms of the Cougaar Open Source License as published on the
 *  Cougaar Open Source Website (www.cougaar.org).
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * </copyright>
 */

/*
 * File:           SocietyHandlerInterface.java
 * Date:           August 27, 2003  4:55 PM
 *
 * @author  Administrator
 * @version generated by NetBeans XML module
 */
package org.cougaar.coordinator.tools;

import org.xml.sax.*;

public interface SocietyHandlerInterface extends ContentHandler {
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_node(final Attributes meta, SocietyTree tree) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_node() throws SAXException;

    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_agent(final Attributes meta, SocietyTree tree) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_agent() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_host(final Attributes meta, SocietyTree tree) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_host() throws SAXException;
    
    /**
     * A container element start event handling method.
     * @param meta attributes
     */
    public void start_society(final Attributes meta) throws SAXException;
    
    /**
     * A container element end event handling method.
     */
    public void end_society() throws SAXException;
    
}

