/*
 * File:           SocietyHandler.java
 * Date:           August 27, 2003  4:55 PM
 *
 * @author  Administrator
 * @version generated by NetBeans XML module
 */
package org.cougaar.coordinator.tools;

import org.xml.sax.*;

public class SocietyHandler implements SocietyHandlerInterface {
    
    public static final boolean DEBUG = false;

    
    public void start_agent(final Attributes meta, SocietyTree tree) throws SAXException {
        if (DEBUG) System.err.println("start_agent: " + meta.getValue("name"));
        tree.addAgent(meta.getValue("name"));
    }
    
    public void end_agent() throws SAXException {
        if (DEBUG) System.err.println("end_agent()");
    }
    
    
    public void start_node(final Attributes meta, SocietyTree tree) throws SAXException {
        if (DEBUG) System.err.println("start_node: " + meta.getValue("name"));
        tree.addNode(meta.getValue("name"));
    }
    
    public void end_node() throws SAXException {
        if (DEBUG) System.err.println("end_node()");
    }
    
    public void start_host(final Attributes meta, SocietyTree tree) throws SAXException {
        if (DEBUG) System.err.println("start_host: " + meta.getValue("name"));
        tree.addHost(meta.getValue("name"));
    }
    
    public void end_host() throws SAXException {
        if (DEBUG) System.err.println("end_host()");
    }
    
    public void start_society(final Attributes meta) throws SAXException {
        if (DEBUG) System.err.println("start_society: " + meta.getValue("name"));
    }
    
    public void end_society() throws SAXException {
        if (DEBUG) System.err.println("end_society()");
    }
    
    public void characters(char[] values, int param, int param2) throws org.xml.sax.SAXException {
    }
    
    public void endDocument() throws org.xml.sax.SAXException {
    }
    
    public void endElement(String str, String str1, String str2) throws org.xml.sax.SAXException {
    }
    
    public void endPrefixMapping(String str) throws org.xml.sax.SAXException {
    }
    
    public void ignorableWhitespace(char[] values, int param, int param2) throws org.xml.sax.SAXException {
    }
    
    public void processingInstruction(String str, String str1) throws org.xml.sax.SAXException {
    }
    
    public void setDocumentLocator(org.xml.sax.Locator locator) {
    }
    
    public void skippedEntity(String str) throws org.xml.sax.SAXException {
    }
    
    public void startDocument() throws org.xml.sax.SAXException {
    }
    
    public void startElement(String str, String str1, String str2, org.xml.sax.Attributes attributes) throws org.xml.sax.SAXException {
    }
    
    public void startPrefixMapping(String str, String str1) throws org.xml.sax.SAXException {
    }
    
}

