/*
 * TestDiagnosisTechSpec.java
 *
 * Created on March 4, 2004, 2:25 PM
 */

package org.cougaar.coordinator.test.coordination;

import org.cougaar.coordinator.techspec.*;  
import org.cougaar.coordinator.*;  
import org.cougaar.core.util.UID;

import java.util.Set;
import java.util.HashSet;
import java.util.Vector;

/**
 * JUST a shell test class... don't use this!!!
 * @deprecated
 * @author  Administrator
 */
public class TestDiagnosisTechSpec implements DiagnosisTechSpecInterface  {
    
    HashSet pvs;
    
    /** Creates a new instance of TestDiagnosisTechSpec */
    public TestDiagnosisTechSpec() {

        pvs = new HashSet();
        pvs.add("Low Threat");
        pvs.add("Medium Threat");
        pvs.add("High Threat");
        pvs.add("No Threat");
    }
    
    public String getDefaultValue() { return "Low Threat"; }
    
    /** @return the asset type that the threat cares about.
     */
    public AssetType getAssetType() {
        return AssetType.findAssetType("AGENT");
    }
    
    /** @return the vector of monitoring levels that this sensor supports
     *
     */
    public Vector getMonitoringLevels() {
        return null;
    }
    
    /** @return a user-readable name for this TechSpec
     *
     */
    public String getName() {
        return "MyTestDiagnosisTechSpec";
    }
    
    /** @return the possible values that Diagnoses generated by this Sensor can return via getValue()
     */
    public Set getPossibleValues() {
        return pvs;
    }
    
    /** @return a revision string for this TechSpec
     *
     */
    public String getRevision() {
        return "0.1";
    }
    
    /** @return the ThreatTypes associated with this Defense
     */
    public Vector getThreatTypes() {
        return null;
    }
    
    /** @return a unique cougaar level name for this TechSpec
     *
     */
    public UID getUID() {
        return null;
    }
    
    /** Add a DiagnosisProbability
     *
     */
    public void addDiagnosisProbability(DiagnosisProbability dp) {
    }
    
    /** @return the possible values that Diagnoses generated by this Sensor can return via getValue()
     */
    public void addPossibleValue(String v) {
    }
    
    /** @return the DiagnosisProbabilities
     *
     */
    public Vector getDiagnosisProbabilities() {
        return null;
    }
    
    /** @return a revision string for this TechSpec
     *
     */
    public void setRevision(String r) {
    }
    
    /** @return the CrossDiagnosisProbabilities
     *
     */
    public Vector getCrossDiagnosisProbabilities() {
        return null;
    }
    
    /** add a CrossDiagnosisProbability
     *
     */
    public void addCrossDiagnosisProbability(CrossDiagnosis cd) {
    }
    
    /** @return the latency -- the time it takes this sensor to diagnose/notice & report a problem, in milliseconds.
     */
    public int getLatency() { return 0;
    }
    
    /** @return the State Dimension that the sensor is watching.
     */
    public AssetStateDimension getStateDimension() {
        return null;
    }
    
    /** @return the reportingPolicy 
     */
    public int getReportingPolicy() {
        return DiagnosisTechSpecInterface.SNAPSHOT;
    }
}
