/*
 * TestActionTechSpec.java
 *
 * Created on March 4, 2004, 2:17 PM
 */

package org.cougaar.coordinator.test.coordination;
import org.cougaar.coordinator.techspec.*;  
import org.cougaar.coordinator.*;  
import org.cougaar.core.util.UID;

import java.util.Set;
import java.util.HashSet;
import java.util.Vector;

/**
 *
 * @author  Administrator
 */
public class TestActionTechSpec implements ActionTechSpecInterface {
    
    HashSet pvs;
    
    /** Creates a new instance of TestActionTechSpec */
    public TestActionTechSpec() {
        pvs = new HashSet();
        pvs.add("NoEncryption");
        pvs.add("64Encryption");
        pvs.add("128Encryption");
        pvs.add("256Encryption");
    }
    
    /** @return the asset type that the threat cares about.
     */
    public AssetType getAssetType() {
        return AssetType.findAssetType("AGENT");
    }
    
    /** @return a user-readable name for this TechSpec
     *
     */
    public String getName() {
        return "MyTestActionTechSpec";
    }
    
    /** @return the possible values that Actions generated by this Actuator can return via getValue()
     */
    public Set getPossibleValues() {
        
        return pvs;
    }
    
    /** @return a revision string for this TechSpec
     *
     */
    public String getRevision() {
        return "0.1";
    }
    
    /** @return a unique cougaar level name for this TechSpec
     *
     */
    public UID getUID() {
        return null;
    }
    
    /**
     * @return an action description for the specified actionValue taken
     * from the actionRecord.getValue(), which was generated initially from getValueFromXML(). 
     * The tech spec does not know what this conversion is since it didn't have a handle to an Action
     * at start up.
     */
    public ActionDescription getActionDescriptionForValue(Action a, Object actionValue) { 
        return null;
    }
    
    /** @return the ActionDescriptions for this Actuator
     */
    public void addAction(ActionDescription ad) {
    }
    
    /** @return the state dimension that the actuator cares about.
     */
    public AssetStateDimension getStateDimension() {
        return null;
    }
    
    /**
     * Get the type of the action
     */
    public int getActionType() { return ActionTechSpecInterface.CORRECTIVE_ACTIONTYPE; }
    
    /** @return the actions for this actuator. This class returns NULL. */
    public Vector getActions() { return null; }
    
}
