/*
 * TestDiagnosisTechSpec.java
 *
 * Created on March 4, 2004, 2:25 PM
 */

package org.cougaar.coordinator.test.coordination;

import org.cougaar.coordinator.techspec.*;  
import org.cougaar.coordinator.*;  
import org.cougaar.core.util.UID;

import java.util.Set;
import java.util.HashSet;
import java.util.Vector;

/**
 *
 * @author  Administrator
 */
public class TestDiagnosisTechSpec implements DiagnosisTechSpecInterface  {
    
    HashSet pvs;
    
    /** Creates a new instance of TestDiagnosisTechSpec */
    public TestDiagnosisTechSpec() {

        pvs = new HashSet();
        pvs.add("Low Threat");
        pvs.add("Medium Threat");
        pvs.add("High Threat");
        pvs.add("No Threat");
    }
    
    /** @return the asset type that the threat cares about.
     */
    public AssetType getAssetType() {
        return AssetType.findAssetType("AGENT");
    }
    
    /** @return the vector of monitoring levels that this sensor supports
     *
     */
    public Vector getMonitoringLevels() {
        return null;
    }
    
    /** @return a user-readable name for this TechSpec
     *
     */
    public String getName() {
        return "MyTestDiagnosisTechSpec";
    }
    
    /** @return the possible values that Diagnoses generated by this Sensor can return via getValue()
     */
    public Set getPossibleValues() {
        return pvs;
    }
    
    /** @return a revision string for this TechSpec
     *
     */
    public String getRevision() {
        return "0.1";
    }
    
    /** @return the ThreatTypes associated with this Defense
     */
    public Vector getThreatTypes() {
        return null;
    }
    
    /** @return a unique cougaar level name for this TechSpec
     *
     */
    public UID getUID() {
        return null;
    }
    
}
