/*
 * TestDiagnosisTechSpec.java
 *
 * Created on March 4, 2004, 2:25 PM
 *
 * <copyright>
 * 
 *  Copyright 2004 Object Services and Consulting, Inc.
 *  under sponsorship of the Defense Advanced Research Projects
 *  Agency (DARPA).
 *
 *  You can redistribute this software and/or modify it under the
 *  terms of the Cougaar Open Source License as published on the
 *  Cougaar Open Source Website (www.cougaar.org).
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * </copyright>
 */


package org.cougaar.coordinator.test.coordination;

import org.cougaar.coordinator.techspec.*;  
import org.cougaar.coordinator.*;  
import org.cougaar.core.util.UID;

import java.util.Set;
import java.util.HashSet;
import java.util.Vector;

/**
 * JUST a shell test class... don't use this!!!
 * @deprecated
 * @author  Administrator
 */
public class TestDiagnosisTechSpec implements DiagnosisTechSpecInterface  {
    
    HashSet pvs;
    
    /** Creates a new instance of TestDiagnosisTechSpec */
    public TestDiagnosisTechSpec() {

        pvs = new HashSet();
        pvs.add("Low Threat");
        pvs.add("Medium Threat");
        pvs.add("High Threat");
        pvs.add("No Threat");
    }
    
    public String getDefaultValue() { return "Low Threat"; }
    
    /** @return the asset type that the threat cares about.
     */
    public AssetType getAssetType() {
        return AssetType.findAssetType("AGENT");
    }
    
    /** @return the vector of monitoring levels that this sensor supports
     *
     */
    public Vector getMonitoringLevels() {
        return null;
    }
    
    /** @return a user-readable name for this TechSpec
     *
     */
    public String getName() {
        return "MyTestDiagnosisTechSpec";
    }
    
    /** @return the possible values that Diagnoses generated by this Sensor can return via getValue()
     */
    public Set getPossibleValues() {
        return pvs;
    }
    
    /** @return a revision string for this TechSpec
     *
     */
    public String getRevision() {
        return "0.1";
    }
    
    /** @return the ThreatTypes associated with this Defense
     */
    public Vector getThreatTypes() {
        return null;
    }
    
    /** @return a unique cougaar level name for this TechSpec
     *
     */
    public UID getUID() {
        return null;
    }
    
    /** Add a DiagnosisProbability
     *
     */
    public void addDiagnosisProbability(DiagnosisProbability dp) {
    }
    
    /** @return the possible values that Diagnoses generated by this Sensor can return via getValue()
     */
    public void addPossibleValue(String v) {
    }
    
    /** @return the DiagnosisProbabilities
     *
     */
    public Vector getDiagnosisProbabilities() {
        return null;
    }
    
    /** @return a revision string for this TechSpec
     *
     */
    public void setRevision(String r) {
    }
    
    /** @return the CrossDiagnosisProbabilities
     *
     */
    public Vector getCrossDiagnosisProbabilities() {
        return null;
    }
    
    /** add a CrossDiagnosisProbability
     *
     */
    public void addCrossDiagnosisProbability(CrossDiagnosis cd) {
    }
    
    /** @return the latency -- the time it takes this sensor to diagnose/notice & report a problem, in milliseconds.
     */
    public int getLatency() { return 0;
    }
    
    /** @return the State Dimension that the sensor is watching.
     */
    public AssetStateDimension getStateDimension() {
        return null;
    }
    
    /** @return the reportingPolicy 
     */
    public int getReportingPolicy() {
        return DiagnosisTechSpecInterface.SNAPSHOT;
    }
}
