#!/bin/tcsh -f

set SOC="cougaar-a"
set JABBER="net5"

if ($HOSTNAME == 'net1' || $HOSTNAME == 'net2' || $HOSTNAME == 'qing' || $HOSTNAME == 'taper') then
  set SOC="cougaar-b"
  set JABBER="oak"
endif

service acme stop
killall -9 ruby
killall -9 java
rm -rf /usr/local/acme.old
mv /usr/local/acme /usr/local/acme.old
cd /shares/development/cougaar/csmart/acme_service/bin
ruby install.rb -j $JABBER -t /usr/local/acme -p acme_password -v /shares/commercial/java/bin/java -c /shares/development/$SOC
chown -R asmt.asmt /usr/local/acme
chmod g+w -R /usr/local/acme
service acme start
