#!/bin/tcsh -f

set SOC="cougaar-a"

if ($HOSTNAME == 'net1' || $HOSTNAME == 'qing' || $HOSTNAME == 'taper' || $HOSTNAME == 'karen') then
  set SOC="cougaar-b"
endif

service acme stop
killall -9 ruby
killall -9 java
rm -rf /usr/local/acme.old
mv /usr/local/acme /usr/local/acme.old
cd /shares/development/$SOC/csmart/acme_service/bin
ruby install.rb -j net5 -t /usr/local/acme -p acme_password -v /shares/commercial/java/bin/java -c /shares/development/$SOC
chown -R asmt.asmt /usr/local/acme
chmod g+w -R /usr/local/acme
service acme start
