#!/bin/sh

COUGAAR_VERS="HEAD"

COUGAAR_PACKAGES="cougaar.zip cougaar-support.zip cougaar-src.zip cougaar-api.zip"
#COUGAAR_PACKAGES="cougaar.zip cougaar-support.zip"

UL_PACKAGES="AL_bbn_HEAD_HEAD.zip \
AR_bbn_HEAD_HEAD.zip \
AR_common_HEAD_HEAD.zip \
AR_objs_common_HEAD_HEAD.zip \
AR_objs_msglog_HEAD_HEAD.zip \
AR_objs_disconnection_HEAD_HEAD.zip \
AR_objs_deconfliction_B11_0_B11_0.zip \
AR_objs_sensors_HEAD_HEAD.zip \
AR_boeing_exnihilo_HEAD_HEAD.zip \
AR_mic_HEAD_HEAD.zip \
bbn_commons_HEAD_B11_0.zip \
BBN_ulconfigs_HEAD_B11_0.zip \
isat_plugins_HEAD_B11_0.zip \
isat_acme_HEAD_B11_0.zip \
isat_oplan_HEAD_B11_0.zip \
AS_csi_secserv_HEAD_HEAD.zip \
AS_csi_overlay_HEAD_HEAD.zip \
SRI_cnc_HEAD_B11_0.zip \
SRI_auto_HEAD_B11_0.zip"

FCSUA_PACKAGES="fcsua_HEAD.zip"

mkdir -p $1
mkdir -p $1/zips
chgrp asmt $1
chmod +s $1
cd $1

for package in $COUGAAR_PACKAGES
do
  wget http://www.alpine.bbn.com/~mthome/autobuild/$COUGAAR_VERS/latest_success/$package --output-document=zips/$package
  unzip -o zips/$package > /dev/null
done

for package in $UL_PACKAGES
do
  wget https://cvs.ultralog.net/dist/$package --http-user=TICCVS --http-passwd=T1CCVS --output-document=zips/$package
  unzip -o zips/$package > /dev/null
done

for package in $FCSUA_PACKAGES
do
  wget http://www.alpine.bbn.com/~ahelsing/autobuild/HEAD/latest_success/$package --output-document=zips/$package
  unzip -o zips/$package > /dev/null
done

cd csmart/config/societies/ad
unzip -o 1ad-configs.zip > /dev/null
cd ../ua
unzip -o ua-configs.zip > /dev/null
cd ../../../..

cp -f robustness/configs/loggingConfig.conf configs/common
cp -f robustness/configs/mic-local/mic.rule csmart/config/rules/robustness/uc1

cd ..
chgrp -R asmt $1
chmod g+w -R $1
